// Generic ReportData → PDF (pdfkit). Title + period + KPI grid + a paginated
// table that repeats its header on each page. pdfkit is in
// serverExternalPackages (next.config.ts).
import 'server-only';
import PDFDocument from 'pdfkit';
import type { ReportData } from './types';
import { formatCell } from './format';

const MARGIN = 40;
const PAGE_W = 841.89; // A4 landscape — reports are wide tables
const PAGE_H = 595.28;
const CONTENT_W = PAGE_W - MARGIN * 2;

export function renderReportPdf(report: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: MARGIN });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = MARGIN;
    const right = MARGIN + CONTENT_W;
    const bottom = PAGE_H - MARGIN;

    // ── Header ──────────────────────────────────────────────────────────
    doc.fillColor('#16322d').font('Helvetica-Bold').fontSize(17).text(report.title, left, MARGIN);
    doc.moveDown(0.2);
    doc.fillColor('#666666').font('Helvetica').fontSize(9);
    if (report.period) doc.text(`Period  ${report.period.label}`);
    doc.text(`Generated  ${new Date(report.generatedAt).toLocaleString('en-US')}`);
    doc.moveDown(0.5);

    // ── KPI grid ────────────────────────────────────────────────────────
    if (report.kpis.length) {
      const perRow = 4;
      const boxW = CONTENT_W / perRow;
      let y = doc.y;
      report.kpis.forEach((kpi, i) => {
        const col = i % perRow;
        const x = left + col * boxW;
        if (col === 0 && i > 0) y += 42;
        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor('#888888')
          .text(kpi.label.toUpperCase(), x, y, { width: boxW - 10 });
        doc
          .font('Helvetica-Bold')
          .fontSize(13)
          .fillColor('#111111')
          .text(kpi.value, x, y + 11, { width: boxW - 10 });
      });
      doc.y = y + 42;
      doc.moveDown(0.6);
    }

    // ── Table ───────────────────────────────────────────────────────────
    const cols = report.columns;
    // Give the first (usually name) column more room; split the rest evenly.
    const firstW = Math.min(180, CONTENT_W * 0.28);
    const restW = (CONTENT_W - firstW) / Math.max(1, cols.length - 1);
    const colX = cols.map((_, i) => left + (i === 0 ? 0 : firstW + (i - 1) * restW));
    const colW = cols.map((_, i) => (i === 0 ? firstW : restW));
    const alignFor = (i: number): 'left' | 'right' =>
      cols[i]?.format && cols[i]?.format !== 'text' && cols[i]?.format !== 'date' && i !== 0
        ? 'right'
        : 'left';

    const drawHeader = (): void => {
      const y = doc.y;
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#666666');
      cols.forEach((c, i) => {
        doc.text(c.label, colX[i]!, y, { width: colW[i]! - 6, align: alignFor(i) });
      });
      doc
        .moveTo(left, y + 12)
        .lineTo(right, y + 12)
        .strokeColor('#cccccc')
        .lineWidth(0.75)
        .stroke();
      doc.y = y + 16;
    };

    drawHeader();
    doc.font('Helvetica').fontSize(8).fillColor('#111111');
    for (const row of report.rows) {
      if (doc.y > bottom - 24) {
        doc.addPage();
        drawHeader();
        doc.font('Helvetica').fontSize(8).fillColor('#111111');
      }
      const y = doc.y;
      let rowH = 10;
      cols.forEach((c, i) => {
        const text = formatCell(row[c.key] ?? null, c.format);
        doc.text(text, colX[i]!, y, { width: colW[i]! - 6, align: alignFor(i) });
        rowH = Math.max(rowH, doc.y - y);
      });
      doc.y = y + rowH + 3;
      doc
        .moveTo(left, doc.y - 1.5)
        .lineTo(right, doc.y - 1.5)
        .strokeColor('#eeeeee')
        .lineWidth(0.5)
        .stroke();
    }

    if (report.rows.length === 0) {
      doc.font('Helvetica-Oblique').fillColor('#999999').text('No data for this period.', left);
    }

    // ── Notes ───────────────────────────────────────────────────────────
    if (report.notes?.length) {
      doc.moveDown(1);
      doc.font('Helvetica').fontSize(7).fillColor('#999999');
      for (const n of report.notes) doc.text(`• ${n}`, { width: CONTENT_W });
    }
    doc.moveDown(0.6);
    doc.fillColor('#bbbbbb').fontSize(7).text('Generated by Vendylio', { width: CONTENT_W });

    doc.end();
  });
}
