import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Bookmark,
  Briefcase,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clipboard,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Laptop,
  LifeBuoy,
  Lightbulb,
  Link2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Package,
  Phone,
  PieChart,
  Plus,
  Rocket,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  Smartphone,
  Star,
  Store,
  Trash2,
  TrendingUp,
  Truck,
  User,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react';

const ICONS = {
  'alert-circle': AlertCircle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bar-chart-3': BarChart3,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  clipboard: Clipboard,
  clock: Clock,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'help-circle': HelpCircle,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  laptop: Laptop,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  link: Link2,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  package: Package,
  phone: Phone,
  'pie-chart': PieChart,
  plus: Plus,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  smartphone: Smartphone,
  star: Star,
  store: Store,
  trash: Trash2,
  'trending-up': TrendingUp,
  truck: Truck,
  user: User,
  users: Users,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  i,
  size = 18,
  className,
}: {
  i: IconName;
  size?: number;
  className?: string;
}) {
  const Component = ICONS[i];
  return <Component size={size} className={className} aria-hidden="true" />;
}
